spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/spring?createDatabaseIfNotExist=true
    username: postgres
    password: root
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.postgresql.Driver

  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  #  JavaMail Configuration
  #  https://stackoverflow.com/questions/35347269/javax-mail-authenticationfailedexception-535-5-7-8-username-and-password-not-ac
  #  https://security.google.com/settings/security/apppasswords
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: janupavaripalliriyaz@gmail.com
    password: Khan#2244
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  thymeleaf Configuration
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

#server:
#  port: 5555

#Disabling White-Label error
server:
  error:
    whitelabel:
      enabled: false